// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ngee_precompute_index_cpp
Rcpp::List ngee_precompute_index_cpp(const arma::mat& cluster_id, const std::string& corstr, const bool validate_sorted, const bool validate_balanced);
RcppExport SEXP _networkGEE_ngee_precompute_index_cpp(SEXP cluster_idSEXP, SEXP corstrSEXP, SEXP validate_sortedSEXP, SEXP validate_balancedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cluster_id(cluster_idSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< const bool >::type validate_sorted(validate_sortedSEXP);
    Rcpp::traits::input_parameter< const bool >::type validate_balanced(validate_balancedSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_precompute_index_cpp(cluster_id, corstr, validate_sorted, validate_balanced));
    return rcpp_result_gen;
END_RCPP
}
// ngee_sample_index_cpp
Rcpp::List ngee_sample_index_cpp(const Rcpp::List& index_data, const arma::uvec& batch_size, const bool replace);
RcppExport SEXP _networkGEE_ngee_sample_index_cpp(SEXP index_dataSEXP, SEXP batch_sizeSEXP, SEXP replaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< const bool >::type replace(replaceSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_sample_index_cpp(index_data, batch_size, replace));
    return rcpp_result_gen;
END_RCPP
}
// ngee_kernel_det_hier_cpp
Rcpp::List ngee_kernel_det_hier_cpp(const arma::colvec& beta, const double phi, const arma::colvec& rho, const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, const std::string& corstr, const double rho_eps);
RcppExport SEXP _networkGEE_ngee_kernel_det_hier_cpp(SEXP betaSEXP, SEXP phiSEXP, SEXP rhoSEXP, SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP corstrSEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_kernel_det_hier_cpp(beta, phi, rho, outcome, design_mat, index_data, family, corstr, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// ngee_fit_det_hier_cpp
Rcpp::List ngee_fit_det_hier_cpp(const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, const std::string& corstr, arma::colvec beta0, double phi0, arma::colvec rho0, const double tol, const int maxit, const double phi_min, const double rho_eps);
RcppExport SEXP _networkGEE_ngee_fit_det_hier_cpp(SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP corstrSEXP, SEXP beta0SEXP, SEXP phi0SEXP, SEXP rho0SEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP phi_minSEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type phi_min(phi_minSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_fit_det_hier_cpp(outcome, design_mat, index_data, family, corstr, beta0, phi0, rho0, tol, maxit, phi_min, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// ngee_hier_sandwich_blocks_cpp
Rcpp::List ngee_hier_sandwich_blocks_cpp(const arma::colvec& beta, const double phi, const arma::colvec& rho, const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, const std::string& corstr, const double rho_eps);
RcppExport SEXP _networkGEE_ngee_hier_sandwich_blocks_cpp(SEXP betaSEXP, SEXP phiSEXP, SEXP rhoSEXP, SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP corstrSEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_hier_sandwich_blocks_cpp(beta, phi, rho, outcome, design_mat, index_data, family, corstr, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// ngee_hier_sandwich_det_cpp
Rcpp::List ngee_hier_sandwich_det_cpp(const arma::colvec& beta, const double phi, const arma::colvec& rho, const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, const std::string& corstr, const std::string& se_adjust, const double fg_cap, const double rho_eps);
RcppExport SEXP _networkGEE_ngee_hier_sandwich_det_cpp(SEXP betaSEXP, SEXP phiSEXP, SEXP rhoSEXP, SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP corstrSEXP, SEXP se_adjustSEXP, SEXP fg_capSEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type se_adjust(se_adjustSEXP);
    Rcpp::traits::input_parameter< const double >::type fg_cap(fg_capSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_hier_sandwich_det_cpp(beta, phi, rho, outcome, design_mat, index_data, family, corstr, se_adjust, fg_cap, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// ngee_fit_det_hier_se_cpp
Rcpp::List ngee_fit_det_hier_se_cpp(const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, const std::string& corstr, arma::colvec beta0, double phi0, arma::colvec rho0, const std::string& se_adjust, const double tol, const int maxit, const double phi_min, const double fg_cap, const double rho_eps);
RcppExport SEXP _networkGEE_ngee_fit_det_hier_se_cpp(SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP corstrSEXP, SEXP beta0SEXP, SEXP phi0SEXP, SEXP rho0SEXP, SEXP se_adjustSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP phi_minSEXP, SEXP fg_capSEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type se_adjust(se_adjustSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type phi_min(phi_minSEXP);
    Rcpp::traits::input_parameter< const double >::type fg_cap(fg_capSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_fit_det_hier_se_cpp(outcome, design_mat, index_data, family, corstr, beta0, phi0, rho0, se_adjust, tol, maxit, phi_min, fg_cap, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// ngee_kernel_det_tscs_cpp
Rcpp::List ngee_kernel_det_tscs_cpp(const arma::colvec& beta, const double phi, const arma::colvec& rho, const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, const double rho_eps);
RcppExport SEXP _networkGEE_ngee_kernel_det_tscs_cpp(SEXP betaSEXP, SEXP phiSEXP, SEXP rhoSEXP, SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_kernel_det_tscs_cpp(beta, phi, rho, outcome, design_mat, index_data, family, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// ngee_fit_det_tscs_cpp
Rcpp::List ngee_fit_det_tscs_cpp(const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, arma::colvec beta0, double phi0, arma::colvec rho0, const double tol, const int maxit, const double phi_min, const double rho_eps);
RcppExport SEXP _networkGEE_ngee_fit_det_tscs_cpp(SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP beta0SEXP, SEXP phi0SEXP, SEXP rho0SEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP phi_minSEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type phi_min(phi_minSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_fit_det_tscs_cpp(outcome, design_mat, index_data, family, beta0, phi0, rho0, tol, maxit, phi_min, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// ngee_tscs_sandwich_blocks_cpp
Rcpp::List ngee_tscs_sandwich_blocks_cpp(const arma::colvec& beta, const double phi, const arma::colvec& rho, const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, const double rho_eps);
RcppExport SEXP _networkGEE_ngee_tscs_sandwich_blocks_cpp(SEXP betaSEXP, SEXP phiSEXP, SEXP rhoSEXP, SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_tscs_sandwich_blocks_cpp(beta, phi, rho, outcome, design_mat, index_data, family, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// ngee_tscs_sandwich_det_cpp
Rcpp::List ngee_tscs_sandwich_det_cpp(const arma::colvec& beta, const double phi, const arma::colvec& rho, const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, const std::string& se_adjust, const double fg_cap, const double rho_eps);
RcppExport SEXP _networkGEE_ngee_tscs_sandwich_det_cpp(SEXP betaSEXP, SEXP phiSEXP, SEXP rhoSEXP, SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP se_adjustSEXP, SEXP fg_capSEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type se_adjust(se_adjustSEXP);
    Rcpp::traits::input_parameter< const double >::type fg_cap(fg_capSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_tscs_sandwich_det_cpp(beta, phi, rho, outcome, design_mat, index_data, family, se_adjust, fg_cap, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// ngee_fit_det_tscs_se_cpp
Rcpp::List ngee_fit_det_tscs_se_cpp(const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, arma::colvec beta0, double phi0, arma::colvec rho0, const std::string& se_adjust, const double tol, const int maxit, const double phi_min, const double fg_cap, const double rho_eps);
RcppExport SEXP _networkGEE_ngee_fit_det_tscs_se_cpp(SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP beta0SEXP, SEXP phi0SEXP, SEXP rho0SEXP, SEXP se_adjustSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP phi_minSEXP, SEXP fg_capSEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type se_adjust(se_adjustSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type phi_min(phi_minSEXP);
    Rcpp::traits::input_parameter< const double >::type fg_cap(fg_capSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_fit_det_tscs_se_cpp(outcome, design_mat, index_data, family, beta0, phi0, rho0, se_adjust, tol, maxit, phi_min, fg_cap, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// ngee_fit_stoch_hier_cpp
Rcpp::List ngee_fit_stoch_hier_cpp(const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, const std::string& corstr, arma::colvec beta0, double phi0, arma::colvec rho0, const arma::uvec& batch_size, const int burnin, const int avgiter, const double phi_min, const double rho_eps, const bool final_refine);
RcppExport SEXP _networkGEE_ngee_fit_stoch_hier_cpp(SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP corstrSEXP, SEXP beta0SEXP, SEXP phi0SEXP, SEXP rho0SEXP, SEXP batch_sizeSEXP, SEXP burninSEXP, SEXP avgiterSEXP, SEXP phi_minSEXP, SEXP rho_epsSEXP, SEXP final_refineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type avgiter(avgiterSEXP);
    Rcpp::traits::input_parameter< const double >::type phi_min(phi_minSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    Rcpp::traits::input_parameter< const bool >::type final_refine(final_refineSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_fit_stoch_hier_cpp(outcome, design_mat, index_data, family, corstr, beta0, phi0, rho0, batch_size, burnin, avgiter, phi_min, rho_eps, final_refine));
    return rcpp_result_gen;
END_RCPP
}
// ngee_fit_stoch_hier_se_cpp
Rcpp::List ngee_fit_stoch_hier_se_cpp(const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, const std::string& corstr, arma::colvec beta0, double phi0, arma::colvec rho0, const arma::uvec& batch_size, const std::string& se_adjust, const int burnin, const int avgiter, const double phi_min, const double fg_cap, const double rho_eps, const bool final_refine);
RcppExport SEXP _networkGEE_ngee_fit_stoch_hier_se_cpp(SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP corstrSEXP, SEXP beta0SEXP, SEXP phi0SEXP, SEXP rho0SEXP, SEXP batch_sizeSEXP, SEXP se_adjustSEXP, SEXP burninSEXP, SEXP avgiterSEXP, SEXP phi_minSEXP, SEXP fg_capSEXP, SEXP rho_epsSEXP, SEXP final_refineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type se_adjust(se_adjustSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type avgiter(avgiterSEXP);
    Rcpp::traits::input_parameter< const double >::type phi_min(phi_minSEXP);
    Rcpp::traits::input_parameter< const double >::type fg_cap(fg_capSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    Rcpp::traits::input_parameter< const bool >::type final_refine(final_refineSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_fit_stoch_hier_se_cpp(outcome, design_mat, index_data, family, corstr, beta0, phi0, rho0, batch_size, se_adjust, burnin, avgiter, phi_min, fg_cap, rho_eps, final_refine));
    return rcpp_result_gen;
END_RCPP
}
// ngee_fit_stoch_tscs_cpp
Rcpp::List ngee_fit_stoch_tscs_cpp(const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, arma::colvec beta0, double phi0, arma::colvec rho0, const arma::uvec& batch_size, const int burnin, const int avgiter, const double phi_min, const double rho_eps, const bool final_refine);
RcppExport SEXP _networkGEE_ngee_fit_stoch_tscs_cpp(SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP beta0SEXP, SEXP phi0SEXP, SEXP rho0SEXP, SEXP batch_sizeSEXP, SEXP burninSEXP, SEXP avgiterSEXP, SEXP phi_minSEXP, SEXP rho_epsSEXP, SEXP final_refineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type avgiter(avgiterSEXP);
    Rcpp::traits::input_parameter< const double >::type phi_min(phi_minSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    Rcpp::traits::input_parameter< const bool >::type final_refine(final_refineSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_fit_stoch_tscs_cpp(outcome, design_mat, index_data, family, beta0, phi0, rho0, batch_size, burnin, avgiter, phi_min, rho_eps, final_refine));
    return rcpp_result_gen;
END_RCPP
}
// ngee_fit_stoch_tscs_se_cpp
Rcpp::List ngee_fit_stoch_tscs_se_cpp(const arma::colvec& outcome, const arma::mat& design_mat, const Rcpp::List& index_data, const std::string& family, arma::colvec beta0, double phi0, arma::colvec rho0, const arma::uvec& batch_size, const std::string& se_adjust, const int burnin, const int avgiter, const double phi_min, const double fg_cap, const double rho_eps, const bool final_refine);
RcppExport SEXP _networkGEE_ngee_fit_stoch_tscs_se_cpp(SEXP outcomeSEXP, SEXP design_matSEXP, SEXP index_dataSEXP, SEXP familySEXP, SEXP beta0SEXP, SEXP phi0SEXP, SEXP rho0SEXP, SEXP batch_sizeSEXP, SEXP se_adjustSEXP, SEXP burninSEXP, SEXP avgiterSEXP, SEXP phi_minSEXP, SEXP fg_capSEXP, SEXP rho_epsSEXP, SEXP final_refineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type index_data(index_dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type se_adjust(se_adjustSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type avgiter(avgiterSEXP);
    Rcpp::traits::input_parameter< const double >::type phi_min(phi_minSEXP);
    Rcpp::traits::input_parameter< const double >::type fg_cap(fg_capSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_eps(rho_epsSEXP);
    Rcpp::traits::input_parameter< const bool >::type final_refine(final_refineSEXP);
    rcpp_result_gen = Rcpp::wrap(ngee_fit_stoch_tscs_se_cpp(outcome, design_mat, index_data, family, beta0, phi0, rho0, batch_size, se_adjust, burnin, avgiter, phi_min, fg_cap, rho_eps, final_refine));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_networkGEE_ngee_precompute_index_cpp", (DL_FUNC) &_networkGEE_ngee_precompute_index_cpp, 4},
    {"_networkGEE_ngee_sample_index_cpp", (DL_FUNC) &_networkGEE_ngee_sample_index_cpp, 3},
    {"_networkGEE_ngee_kernel_det_hier_cpp", (DL_FUNC) &_networkGEE_ngee_kernel_det_hier_cpp, 9},
    {"_networkGEE_ngee_fit_det_hier_cpp", (DL_FUNC) &_networkGEE_ngee_fit_det_hier_cpp, 12},
    {"_networkGEE_ngee_hier_sandwich_blocks_cpp", (DL_FUNC) &_networkGEE_ngee_hier_sandwich_blocks_cpp, 9},
    {"_networkGEE_ngee_hier_sandwich_det_cpp", (DL_FUNC) &_networkGEE_ngee_hier_sandwich_det_cpp, 11},
    {"_networkGEE_ngee_fit_det_hier_se_cpp", (DL_FUNC) &_networkGEE_ngee_fit_det_hier_se_cpp, 14},
    {"_networkGEE_ngee_kernel_det_tscs_cpp", (DL_FUNC) &_networkGEE_ngee_kernel_det_tscs_cpp, 8},
    {"_networkGEE_ngee_fit_det_tscs_cpp", (DL_FUNC) &_networkGEE_ngee_fit_det_tscs_cpp, 11},
    {"_networkGEE_ngee_tscs_sandwich_blocks_cpp", (DL_FUNC) &_networkGEE_ngee_tscs_sandwich_blocks_cpp, 8},
    {"_networkGEE_ngee_tscs_sandwich_det_cpp", (DL_FUNC) &_networkGEE_ngee_tscs_sandwich_det_cpp, 10},
    {"_networkGEE_ngee_fit_det_tscs_se_cpp", (DL_FUNC) &_networkGEE_ngee_fit_det_tscs_se_cpp, 13},
    {"_networkGEE_ngee_fit_stoch_hier_cpp", (DL_FUNC) &_networkGEE_ngee_fit_stoch_hier_cpp, 14},
    {"_networkGEE_ngee_fit_stoch_hier_se_cpp", (DL_FUNC) &_networkGEE_ngee_fit_stoch_hier_se_cpp, 16},
    {"_networkGEE_ngee_fit_stoch_tscs_cpp", (DL_FUNC) &_networkGEE_ngee_fit_stoch_tscs_cpp, 13},
    {"_networkGEE_ngee_fit_stoch_tscs_se_cpp", (DL_FUNC) &_networkGEE_ngee_fit_stoch_tscs_se_cpp, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_networkGEE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
