# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ngee_precompute_index_cpp <- function(cluster_id, corstr, validate_sorted = TRUE, validate_balanced = TRUE) {
    .Call(`_networkGEE_ngee_precompute_index_cpp`, cluster_id, corstr, validate_sorted, validate_balanced)
}

ngee_sample_index_cpp <- function(index_data, batch_size, replace = FALSE) {
    .Call(`_networkGEE_ngee_sample_index_cpp`, index_data, batch_size, replace)
}

ngee_kernel_det_hier_cpp <- function(beta, phi, rho, outcome, design_mat, index_data, family, corstr, rho_eps = 1e-4) {
    .Call(`_networkGEE_ngee_kernel_det_hier_cpp`, beta, phi, rho, outcome, design_mat, index_data, family, corstr, rho_eps)
}

ngee_fit_det_hier_cpp <- function(outcome, design_mat, index_data, family, corstr, beta0, phi0, rho0, tol = 1e-8, maxit = 200L, phi_min = 1e-8, rho_eps = 1e-4) {
    .Call(`_networkGEE_ngee_fit_det_hier_cpp`, outcome, design_mat, index_data, family, corstr, beta0, phi0, rho0, tol, maxit, phi_min, rho_eps)
}

ngee_hier_sandwich_blocks_cpp <- function(beta, phi, rho, outcome, design_mat, index_data, family, corstr, rho_eps = 1e-4) {
    .Call(`_networkGEE_ngee_hier_sandwich_blocks_cpp`, beta, phi, rho, outcome, design_mat, index_data, family, corstr, rho_eps)
}

ngee_hier_sandwich_det_cpp <- function(beta, phi, rho, outcome, design_mat, index_data, family, corstr, se_adjust = "unadjusted", fg_cap = 0.85, rho_eps = 1e-4) {
    .Call(`_networkGEE_ngee_hier_sandwich_det_cpp`, beta, phi, rho, outcome, design_mat, index_data, family, corstr, se_adjust, fg_cap, rho_eps)
}

ngee_fit_det_hier_se_cpp <- function(outcome, design_mat, index_data, family, corstr, beta0, phi0, rho0, se_adjust = "unadjusted", tol = 1e-8, maxit = 200L, phi_min = 1e-8, fg_cap = 0.85, rho_eps = 1e-4) {
    .Call(`_networkGEE_ngee_fit_det_hier_se_cpp`, outcome, design_mat, index_data, family, corstr, beta0, phi0, rho0, se_adjust, tol, maxit, phi_min, fg_cap, rho_eps)
}

ngee_kernel_det_tscs_cpp <- function(beta, phi, rho, outcome, design_mat, index_data, family, rho_eps = 1e-4) {
    .Call(`_networkGEE_ngee_kernel_det_tscs_cpp`, beta, phi, rho, outcome, design_mat, index_data, family, rho_eps)
}

ngee_fit_det_tscs_cpp <- function(outcome, design_mat, index_data, family, beta0, phi0, rho0, tol = 1e-8, maxit = 200L, phi_min = 1e-8, rho_eps = 1e-4) {
    .Call(`_networkGEE_ngee_fit_det_tscs_cpp`, outcome, design_mat, index_data, family, beta0, phi0, rho0, tol, maxit, phi_min, rho_eps)
}

ngee_tscs_sandwich_blocks_cpp <- function(beta, phi, rho, outcome, design_mat, index_data, family, rho_eps = 1e-4) {
    .Call(`_networkGEE_ngee_tscs_sandwich_blocks_cpp`, beta, phi, rho, outcome, design_mat, index_data, family, rho_eps)
}

ngee_tscs_sandwich_det_cpp <- function(beta, phi, rho, outcome, design_mat, index_data, family, se_adjust = "unadjusted", fg_cap = 0.85, rho_eps = 1e-4) {
    .Call(`_networkGEE_ngee_tscs_sandwich_det_cpp`, beta, phi, rho, outcome, design_mat, index_data, family, se_adjust, fg_cap, rho_eps)
}

ngee_fit_det_tscs_se_cpp <- function(outcome, design_mat, index_data, family, beta0, phi0, rho0, se_adjust = "unadjusted", tol = 1e-8, maxit = 200L, phi_min = 1e-8, fg_cap = 0.85, rho_eps = 1e-4) {
    .Call(`_networkGEE_ngee_fit_det_tscs_se_cpp`, outcome, design_mat, index_data, family, beta0, phi0, rho0, se_adjust, tol, maxit, phi_min, fg_cap, rho_eps)
}

ngee_fit_stoch_hier_cpp <- function(outcome, design_mat, index_data, family, corstr, beta0, phi0, rho0, batch_size, burnin = 50L, avgiter = 50L, phi_min = 1e-8, rho_eps = 1e-4, final_refine = TRUE) {
    .Call(`_networkGEE_ngee_fit_stoch_hier_cpp`, outcome, design_mat, index_data, family, corstr, beta0, phi0, rho0, batch_size, burnin, avgiter, phi_min, rho_eps, final_refine)
}

ngee_fit_stoch_hier_se_cpp <- function(outcome, design_mat, index_data, family, corstr, beta0, phi0, rho0, batch_size, se_adjust = "unadjusted", burnin = 50L, avgiter = 50L, phi_min = 1e-8, fg_cap = 0.85, rho_eps = 1e-4, final_refine = TRUE) {
    .Call(`_networkGEE_ngee_fit_stoch_hier_se_cpp`, outcome, design_mat, index_data, family, corstr, beta0, phi0, rho0, batch_size, se_adjust, burnin, avgiter, phi_min, fg_cap, rho_eps, final_refine)
}

ngee_fit_stoch_tscs_cpp <- function(outcome, design_mat, index_data, family, beta0, phi0, rho0, batch_size, burnin = 50L, avgiter = 50L, phi_min = 1e-8, rho_eps = 1e-4, final_refine = TRUE) {
    .Call(`_networkGEE_ngee_fit_stoch_tscs_cpp`, outcome, design_mat, index_data, family, beta0, phi0, rho0, batch_size, burnin, avgiter, phi_min, rho_eps, final_refine)
}

ngee_fit_stoch_tscs_se_cpp <- function(outcome, design_mat, index_data, family, beta0, phi0, rho0, batch_size, se_adjust = "unadjusted", burnin = 50L, avgiter = 50L, phi_min = 1e-8, fg_cap = 0.85, rho_eps = 1e-4, final_refine = TRUE) {
    .Call(`_networkGEE_ngee_fit_stoch_tscs_se_cpp`, outcome, design_mat, index_data, family, beta0, phi0, rho0, batch_size, se_adjust, burnin, avgiter, phi_min, fg_cap, rho_eps, final_refine)
}

