# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Seq <- function(first, last) {
    .Call(`_networkGEE_Seq`, first, last)
}

mypmin <- function(vec1, vec2) {
    .Call(`_networkGEE_mypmin`, vec1, vec2)
}

myrep <- function(x, y) {
    .Call(`_networkGEE_myrep`, x, y)
}

myrep_uvec <- function(x, y) {
    .Call(`_networkGEE_myrep_uvec`, x, y)
}

colSums <- function(X) {
    .Call(`_networkGEE_colSums`, X)
}

mycombnCpp <- function(n, k) {
    .Call(`_networkGEE_mycombnCpp`, n, k)
}

pairwiseprod <- function(M) {
    .Call(`_networkGEE_pairwiseprod`, M)
}

pairwiseprod2 <- function(M, N, dir) {
    .Call(`_networkGEE_pairwiseprod2`, M, N, dir)
}

arma_setdiff <- function(x, y) {
    .Call(`_networkGEE_arma_setdiff`, x, y)
}

index_fun2 <- function(J) {
    .Call(`_networkGEE_index_fun2`, J)
}

index_fun1 <- function(J) {
    .Call(`_networkGEE_index_fun1`, J)
}

combine <- function(list) {
    .Call(`_networkGEE_combine`, list)
}

cluster_characteristics <- function(clusterid) {
    .Call(`_networkGEE_cluster_characteristics`, clusterid)
}

hierarchical_sampling <- function(I_idx, batch, replace, tscs) {
    .Call(`_networkGEE_hierarchical_sampling`, I_idx, batch, replace, tscs)
}

rcpp_lengths_recursive <- function(lst) {
    .Call(`_networkGEE_rcpp_lengths_recursive`, lst)
}

rcpp_lengths <- function(lst) {
    .Call(`_networkGEE_rcpp_lengths`, lst)
}

binomial_hier_solver <- function(beta, rho, outcome, design_mat, Info1, I_idx) {
    .Call(`_networkGEE_binomial_hier_solver`, beta, rho, outcome, design_mat, Info1, I_idx)
}

gaussian_hier_solver <- function(beta, phi, rho, outcome, design_mat, Info1, I_idx) {
    .Call(`_networkGEE_gaussian_hier_solver`, beta, phi, rho, outcome, design_mat, Info1, I_idx)
}

binomial_hier_sandwich <- function(beta, rho, outcome, design_mat, I_idx) {
    .Call(`_networkGEE_binomial_hier_sandwich`, beta, rho, outcome, design_mat, I_idx)
}

gaussian_hier_sandwich <- function(beta, phi, rho, outcome, design_mat, I_idx) {
    .Call(`_networkGEE_gaussian_hier_sandwich`, beta, phi, rho, outcome, design_mat, I_idx)
}

binomial_tscs_solver <- function(beta, rho, outcome, design_mat, Info1, I_idx) {
    .Call(`_networkGEE_binomial_tscs_solver`, beta, rho, outcome, design_mat, Info1, I_idx)
}

gaussian_tscs_solver <- function(beta, phi, rho, outcome, design_mat, Info1, I_idx) {
    .Call(`_networkGEE_gaussian_tscs_solver`, beta, phi, rho, outcome, design_mat, Info1, I_idx)
}

binomial_tscs_sandwich <- function(beta, phi, rho, outcome, design_mat, I_idx) {
    .Call(`_networkGEE_binomial_tscs_sandwich`, beta, phi, rho, outcome, design_mat, I_idx)
}

gaussian_tscs_sandwich <- function(beta, phi, rho, outcome, design_mat, I_idx) {
    .Call(`_networkGEE_gaussian_tscs_sandwich`, beta, phi, rho, outcome, design_mat, I_idx)
}

stochastic_binomial_hier_solver <- function(beta, rho, outcome, design_mat, I_idx, I_full, J_full, K_full) {
    .Call(`_networkGEE_stochastic_binomial_hier_solver`, beta, rho, outcome, design_mat, I_idx, I_full, J_full, K_full)
}

stochastic_gaussian_hier_solver <- function(beta, phi, rho, outcome, design_mat, I_idx, I_full, J_full, K_full) {
    .Call(`_networkGEE_stochastic_gaussian_hier_solver`, beta, phi, rho, outcome, design_mat, I_idx, I_full, J_full, K_full)
}

stochastic_binomial_tscs_solver <- function(beta, rho, outcome, design_mat, I_idx, I_full, J_full, K_full) {
    .Call(`_networkGEE_stochastic_binomial_tscs_solver`, beta, rho, outcome, design_mat, I_idx, I_full, J_full, K_full)
}

stochastic_gaussian_tscs_solver <- function(beta, phi, rho, outcome, design_mat, I_idx, I_full, J_full, K_full) {
    .Call(`_networkGEE_stochastic_gaussian_tscs_solver`, beta, phi, rho, outcome, design_mat, I_idx, I_full, J_full, K_full)
}

meat_computation <- function(G, H, Info, se_adjust) {
    .Call(`_networkGEE_meat_computation`, G, H, Info, se_adjust)
}

NewRaph <- function(beta, phi, rho, outcome, design_mat, clusterid, family, corstr, design, se_adjust, tol) {
    .Call(`_networkGEE_NewRaph`, beta, phi, rho, outcome, design_mat, clusterid, family, corstr, design, se_adjust, tol)
}

StochNewRaph <- function(beta, phi, rho, outcome, design_mat, clusterid, family, corstr, design, se_adjust, batch_size, burnin, avgiter) {
    .Call(`_networkGEE_StochNewRaph`, beta, phi, rho, outcome, design_mat, clusterid, family, corstr, design, se_adjust, batch_size, burnin, avgiter)
}

